
import {AbstractObjectHelper, FieldHelper } from "d2f-ngx-crud";
import { Devise } from "../data/devise";

export class DeviseHelper extends AbstractObjectHelper<Devise,String> {
        constructor(){
                super("Devise",false,"code"); //EntityName,withAutoGeneratedId,idKeyName
        }
        getId(obj: Devise): String { return obj.code; };
        buildEmptyObject(): Devise { return new Devise(); };
        initObjectHelper(){
               this.classHelper.essentialFieldNames = ["code","name","change"]
               this.classHelper.fieldHelperMap.set("code",new FieldHelper("code"))
               this.classHelper.fieldHelperMap.set("name",new FieldHelper("name"))
               this.classHelper.fieldHelperMap.set("change",new FieldHelper("change","number",1));
               //NB:FieldHelper(fieldName,fieldType,defaultValue)
        }
}