
import {AbstractObjectHelper, FieldHelper } from "d2f-ngx-util";
import { Product } from "../data/product";

export class ProductHelper extends AbstractObjectHelper<Product,String|null> {
        constructor(){
                super("Product",true,"ref"); //EntityName,withAutoGeneratedId,idKeyName
        }
        getId(obj: Product): String | null { return obj.ref; };
        buildEmptyObject(): Product { return new Product(); };
        initObjectHelper(){
               this.classHelper.essentialFieldNames = ["ref","label","price"];
               this.addFieldHelperWithExtraInfo(new FieldHelper("ref"), { notEditable : true});
               this.addFieldHelper(new FieldHelper("label"))
               this.addFieldHelper(new FieldHelper("price","number",0));
               //NB:FieldHelper(fieldName,fieldType,defaultValue)
               //attention , JSON.stringify( js Map) not display map content !!!
        }
}

