
import {AbstractObjectHelper, FieldHelper } from "d2f-ngx-util";
import { Product } from "../data/product";

export class ProductHelper extends AbstractObjectHelper<Product,String|null> {
        constructor(){
                super("Product",true,"ref"); //EntityName,withAutoGeneratedId,idKeyName
        }
        getId(obj: Product): String | null { return obj.ref; };
        buildEmptyObject(): Product { return new Product(); };
        initObjectHelper(){
               this.classHelper.essentialFieldNames = ["ref","label","price"]
               this.classHelper.fieldHelperMap.set("ref",new FieldHelper("ref"))
               this.classHelper.fieldHelperMap.set("label",new FieldHelper("label"))
               this.classHelper.fieldHelperMap.set("price",new FieldHelper("price","number",0));
               //NB:FieldHelper(fieldName,fieldType,defaultValue)
        }
}

