import { Component, input, InputSignal, model, ModelSignal } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { LabelInputFieldComponent, ReadOnlyFieldComponent } from 'd2f-ngx-forms';
import { ObjectHelper , FieldHelper } from 'd2f-ngx-util';

/*
Version "td" (template-driven)
RESTRICTION IMPORTANTE de cette implementation simple :
pas de remontée "valid" ou "invalid" car trop de niveaux d'imbrications 
*/

@Component({
  selector: 'auto-gen-td-form',
  standalone : true,
  imports: [FormsModule,LabelInputFieldComponent,ReadOnlyFieldComponent],
  templateUrl: './auto-gen-td-form.component.html',
  styleUrl: './auto-gen-td-form.component.css'
})
export class AutoGenTdFormComponent  {


    //[(ngModel)]="deviseTempRef()!.code" , ....
        objectTempRef :ModelSignal<any> = model(null);

        objectHelperRef =input<ObjectHelper<any,any> | null>(null);

        modeRef = model("newOne"); //or "existingOne"

        objectKeysArray(obj:object):any[]{
          return Reflect.ownKeys(obj);
        }
    
        isNoEditableId(attrName:string){
          if(this.objectHelperRef()!.classHelper.idKeyName != attrName) return false;
          /* else is key attr*/
          if(this.objectHelperRef()!.classHelper.withAutoGeneratedId)return true;
          if(this.modeRef()!="newOne") return true;
          return false;
         }

}
